### ISSUE TITLE
Create custom filters to use inside templates

### ISSUE THREAD

**Issue by alefcarlos** [backstage/software-templates#11]
Hi!

As we can see bellow, we can use `parseRepoUrl` filter inside template.

https://github.com/backstage/software-templates/blob/38baabef075ba25689c988cd3ab5e54879f18ce1/scaffolder-templates/docs-template/template.yaml#L66

I'd like to know how can I create a custom function to use.

For example, I'm using `EntityPicker` to list all systems, but the value returned is `system:foo`, but in my parameter i need only entity name.

```
      input:
        template: 'template-ms'
        args:
          - --namespace
          - ${{ parameters.namespace }}
          - --template
          - webapi
          - --app-name
          - ${{ parameters.app_name }}
          - --system
          - ${{ parameters.system | getEntityName}}
          - --team
          - ${{ parameters.team}}
          - --domain
          - ${{ parameters.domain | getEntityName }}
```

So, I would create that `getEntityName `, but I couldn't find any documentation.

Thank you!
