### ISSUE TITLE
No integration for host gitlab.com

### ISSUE THREAD

**Issue by max-bojorquez** [backstage/software-templates#24]
I am using the [create-react-app template](https://github.com/backstage/software-templates/blob/main/scaffolder-templates/create-react-app/template.yaml) sample on my backstage local. I have integration defined in my app-config.yaml file 
```
integrations:
  gitlab:
    - host: gitlab.sample.com
      apiBaseUrl: https://gitlab.sample.com/api/v4
      token:
        $env: GITLAB_TOKEN
```
Everything seems to be going okay, up until I get to the publishing task. Not sure if am entering the correct Owner. I am entering as my user, mbojorq12, and the repository name as *reactTeamplate*. Not sure how specific it would have to be. But I am getting the below integration error. Wondering if I need to add the integration within the template.yaml file

```
[1](http://localhost:3000/create/tasks/f47a9285-ba18-45b3-b427-426aad2f63be#line-1)2022-10-20T20:30:38.000Z Beginning step Publish
[2](http://localhost:3000/create/tasks/f47a9285-ba18-45b3-b427-426aad2f63be#line-2)2022-10-20T20:30:38.000Z InputError: No integration for host gitlab.bankofthewest.com
```
