### ISSUE TITLE
publish:github actions in docs template is not creating "main" branch in github

### ISSUE THREAD

**Issue by prasoon-pxc** [backstage/software-templates#25]
I am using below code in my documentation template to publish repository in github and then configured it in backstage but below template is creating `master` branch in place of `main` branch in github, and due to this many other functionality in github is creating the problem .
And, github is also deprecated `master` branch name as of now
 [Changelog](https://github.blog/changelog/2020-10-01-the-default-branch-for-newly-created-repositories-is-now-main/)

---

- This `actions: publish:github` is creating the `master` branch and required some changes
```
- id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}

    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: "/catalog-info.yaml"
```

**Comment by prasoon-pxc** [comment]
This is resolved by using `branch: main` in input section 
---
```
- id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ["github.com"]
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        branch: main

```
